### ISSUE TITLE
Console Readme

### ISSUE THREAD

**Issue by PiotrStrzalka** [rideskip/anchor#1]
Hello,
I am really impressed with your job! I really enjoy using it!
I found small mistake in Readme file for console, first argument in example is string but should be " a valid C symbol name"

this part:

```
    CONSOLE_STR_ARG_DEF("port", "The port <A,B,C>"),
```
should be:

```
    CONSOLE_STR_ARG_DEF(port, "The port <A,B,C>"),
```
etc.

**Comment by bgomberg** [comment]
Thanks for letting us know! I've pushed a fix for this with 0a93525a8642d9a6bda3acc07b2b19c289f4b735
